- name: F5 configuration - Virtual server
  hosts: localhost
  vars:
    F5_SERVER: "192.168.239.142"
    F5_USER: "dano"
    F5_PASSWORD: "Dano0984"
    F5_SERVER_PORT: "22"
- name: Assigning nodes to LTM pools (nodes_ltm_pools.csv)
  bigip_pool:
    provider:
      server: "{{ F5_SERVER }}"
      user: "{{ F5_USER }}"
      password: "{{ F5_PASSWORD }}"
    state: present
    pool: my_pool
    partition: Common
    port: "80"
  delegate_to: localhost
